pipeline {
    agent any

    environment {
        DEPLOY_SERVER = "ubuntu@172.31.45.164" 
        DEPLOY_PATH = "/var/www/html"           
        GIT_REPO = "https://github.com/harikrishnaB18/Cambridge-application.git"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: env.GIT_REPO
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install' 
                }
            }
        }

        stage('Build React App') {
            steps {
                script {
                    sh 'npm run build'  
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                script {
                    sshagent(['your-ssh-credential-id']) {
                        sh """
                            scp -r build/* ubuntu@172.31.45.164:/var/www/html/
                            ssh ubuntu@172.31.45.164 'sudo systemctl restart nginx'
                        """
                    }
                }
            }
        }
    }
}
